export PATH=$HOME/.brew/bin:$PATH
alias ll="ls -la"
alias source="source ~/.zshrc"
alias myip="curl ipinfo.io/ip"
alias fr="rm -rf"
alias rf="rm -rf"
alias ll="ls -laG"
alias l="ls -lG"
alias cl="clear"
alias ls="ls -G"
alias dd="cd ~/Desktop/"
alias .="pwd"
alias ..="cd .."
alias ...="cd ../../"
alias cs="clear;ls -l"
alias :wa="clear;ls -l"
alias now="date && cal"
alias gcc="gcc -Werror -Wall -Wextra "
#docker
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.112:2376"
export DOCKER_CERT_PATH="/Users/ynoam/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"

export PATH="/goinfre/ynoam/home/scripts/:$HOME/.brown/bin:$PATH"
export PATH="$HOME/.brew/bin:$PATH"
